---
services:
  pydoit:
    build:
      context: .
      dockerfile: Dockerfile
    image: pydoit
    container_name: pydoit
    network_mode: host
    volumes:
      - ./lists:/app/lists
    restart: unless-stopped
