---
services:
  pydoit:
    build:
      context: .
      dockerfile: Dockerfile
    image: pydoit
    container_name: pydoit
    ports:
      - 5006:5006
    # network_mode: host
    volumes:
      - ./lists:/app/lists:rw
    restart: unless-stopped
